-- Remove old services
DELETE FROM "services" WHERE category NOT IN ('cleaning');

-- Update enums
ALTER TYPE "MainCategory" DROP VALUE IF EXISTS 'BEAUTY_AND_WELLNESS';
ALTER TYPE "MainCategory" DROP VALUE IF EXISTS 'TECHNICAL_SERVICES';

ALTER TYPE "ServiceCategory" DROP VALUE IF EXISTS 'HAIR_SERVICES';
ALTER TYPE "ServiceCategory" DROP VALUE IF EXISTS 'NAILS';
ALTER TYPE "ServiceCategory" DROP VALUE IF EXISTS 'PLUMBING';
ALTER TYPE "ServiceCategory" DROP VALUE IF EXISTS 'ELECTRICAL';
ALTER TYPE "ServiceCategory" DROP VALUE IF EXISTS 'GARDENING';
ALTER TYPE "ServiceCategory" DROP VALUE IF EXISTS 'IT_SUPPORT';
ALTER TYPE "ServiceCategory" DROP VALUE IF EXISTS 'SECURITY_SYSTEMS';
