# Actionlint configuration
# Suppresses false positive warnings about GitHub Actions secrets

# Ignore warnings about secret context access
# These are false positives - secrets are valid in GitHub Actions
# but the linter can't verify they exist in the repository
oneline:
  # Allow secret context access without warnings
  - 'secrets\.[A-Z_]+'

# Valid contexts
shellcheck:
  enable: false

# Ignore specific warning patterns
ignore:
  - 'Context access might be invalid'
  - 'Unrecognized named-value.*secrets'
